
name: hish-rag

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./.data/qdrant:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/6333' || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 6
      start_period: 5s

  # LlamaIndex-Compatible Qdrant MCP: main CRUD server
  mcp-qdrant-llamaindex:
    build:
      context: ./mcp
      dockerfile: Dockerfile.llamaindex
    depends_on:
      qdrant:
        condition: service_healthy
    env_file:
      - ./env.mcp
    environment:
      - QDRANT_READ_ONLY=false
    command: ["qdrant-llamaindex-mcp-server", "--transport", "stdio"]
    profiles: ["stdio"]  # invoked interactively



  # Indexer for bulk embedding of framework content
  indexer:
    build:
      context: ./rag/indexer
      dockerfile: Dockerfile
    depends_on:
      qdrant:
        condition: service_healthy
    env_file:
      - ./env.framework
    volumes:
      - .:/work:ro  # Mount only current repository for framework indexing

  indexer-code:
    build:
      context: ./rag/indexer
      dockerfile: Dockerfile
    depends_on:
      qdrant:
        condition: service_healthy
    env_file:
      - ./env.code
    volumes:
      - ../:/work:ro  # Mount the entire projects directory

  # Test service for running pytest
  indexer-test:
    build:
      context: ./rag/indexer
      dockerfile: Dockerfile
      target: test
    environment:
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      COLLECTION_NAME: ${COLLECTION_NAME}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL}
      INDEX_INCLUDE: ${INDEX_INCLUDE}
      INDEX_EXCLUDE: ${INDEX_EXCLUDE}
      CHUNK_MAX_TOKENS: ${CHUNK_MAX_TOKENS}
      CHUNK_MIN_CHARS: ${CHUNK_MIN_CHARS}
      CHUNK_OVERLAP_TOKENS: ${CHUNK_OVERLAP_TOKENS}
    volumes:
      - ./:/work:ro
    profiles: ["test"]  # Only for testing
